FROM node:22-alpine AS base
WORKDIR /usr/local/app

FROM base AS backend-build
COPY backend/. ./
RUN mkdir -p /usr/local/app/uploads
RUN npm install
RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npx prisma generate
RUN npm run build

FROM base AS backend
WORKDIR /usr/local/app
COPY --from=backend-build /usr/local/app/dist ./dist
COPY --from=backend-build /usr/local/app/node_modules ./node_modules
COPY --from=backend-build /usr/local/app/package*.json ./
COPY --from=backend-build /usr/local/app/prisma ./prisma
COPY --from=backend-build /usr/local/app/prisma.config.ts ./
RUN mkdir -p /usr/local/app/uploads
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]

FROM base AS frontend-build
COPY frontend/. ./
ARG FRONTEND_BACKEND_URL
ENV PUBLIC_BACKEND_URL=$FRONTEND_BACKEND_URL
RUN npm install
RUN npm run build

FROM nginx:alpine AS frontend
COPY --from=frontend-build /usr/local/app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

FROM base AS landing-build
COPY landing/. ./
ARG LANDING_FRONTEND_URL
ENV PUBLIC_LANDING_FRONTEND_URL=$LANDING_FRONTEND_URL
RUN npm install
RUN npm run build

FROM nginx:alpine AS landing
COPY --from=landing-build /usr/local/app/dist /usr/share/nginx/html
COPY landing/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
