FROM node:22-alpine AS base
WORKDIR /usr/local/app

FROM base AS backend
COPY backend/. ./
RUN mkdir -p /usr/local/app/uploads
RUN npm install
RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npx prisma generate
CMD ["sh", "-c", "npx prisma migrate dev && npm run dev"]

FROM base AS frontend
COPY frontend/. ./
RUN npm install
CMD ["sh", "-c", "npm run dev"]

FROM base AS landing
COPY landing/. ./
RUN npm install
CMD ["sh", "-c", "npm run dev"]
