FROM node:22-alpine AS base
WORKDIR /usr/local/app
RUN npm install -g pnpm

FROM base AS backend
COPY backend/. ./
RUN mkdir -p /usr/local/app/uploads
RUN pnpm install
CMD ["sh", "-c", "npx prisma migrate dev && pnpm run dev"]

FROM base AS frontend
COPY frontend/. ./
RUN pnpm install
CMD ["sh", "-c", "pnpm run dev"]